apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollyscale-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
    # Depends on CNPG operator being installed first
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: middleware
  source:
    repoURL: "${chart_registry}"
    chart: ollyscale-postgres
    targetRevision: ${postgres_chart_tag}
    helm:
      valuesObject:
        # Use smaller resources for local development
        numberOfInstances: 1
        
        volume:
          size: 5Gi
          storageClass: ''
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        patroni:
          synchronous_mode: false
          synchronous_mode_strict: false
  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollyscale
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
