apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-access-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: middleware
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.service.port
        - .spec.versions[].schema.openAPIV3Schema.properties.spec.properties.*.default
  source:
    repoURL: quay.io
    chart: strimzi-helm/strimzi-access-operator
    targetRevision: 0.2.0
    helm:
      valuesObject:
        watchAnyNamespace: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: strimzi-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
