apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://bedag.github.io/helm-charts/'
    chart: raw
    targetRevision: 2.0.2
    helm:
      values: |
        resources:
          -
            apiVersion: v1
            kind: Namespace
            metadata:
              name: registry
          -
            apiVersion: source.toolkit.fluxcd.io/v1beta2
            kind: HelmRepository
            metadata:
              name: twuni
              namespace: registry
            spec:
              interval: 1h
              url: https://twuni.github.io/docker-registry.helm
          -
            apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            metadata:
              name: docker-registry
              namespace: registry
            spec:
              interval: 5m
              chart:
                spec:
                  chart: docker-registry
                  version: 3.0.0
                  sourceRef:
                    kind: HelmRepository
                    name: twuni
                    namespace: registry
                  interval: 1m
              values:
                service:
                  port: 5000
          -
            apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: docker-registry
              namespace: registry
            spec:
              parentRefs:
                - name: management-gateway
                  namespace: envoy-gateway-system
              hostnames:
                - registry.${gateway_dns_suffix}
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - name: docker-registry
                      port: 5000
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
